// Generated by gencpp from file whatever/flight_mode.msg
// DO NOT EDIT!


#ifndef WHATEVER_MESSAGE_FLIGHT_MODE_H
#define WHATEVER_MESSAGE_FLIGHT_MODE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace whatever
{
template <class ContainerAllocator>
struct flight_mode_
{
  typedef flight_mode_<ContainerAllocator> Type;

  flight_mode_()
    : flight_mode()  {
    }
  flight_mode_(const ContainerAllocator& _alloc)
    : flight_mode(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _flight_mode_type;
  _flight_mode_type flight_mode;





  typedef boost::shared_ptr< ::whatever::flight_mode_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::whatever::flight_mode_<ContainerAllocator> const> ConstPtr;

}; // struct flight_mode_

typedef ::whatever::flight_mode_<std::allocator<void> > flight_mode;

typedef boost::shared_ptr< ::whatever::flight_mode > flight_modePtr;
typedef boost::shared_ptr< ::whatever::flight_mode const> flight_modeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::whatever::flight_mode_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::whatever::flight_mode_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::whatever::flight_mode_<ContainerAllocator1> & lhs, const ::whatever::flight_mode_<ContainerAllocator2> & rhs)
{
  return lhs.flight_mode == rhs.flight_mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::whatever::flight_mode_<ContainerAllocator1> & lhs, const ::whatever::flight_mode_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace whatever

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::whatever::flight_mode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::whatever::flight_mode_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::whatever::flight_mode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::whatever::flight_mode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::whatever::flight_mode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::whatever::flight_mode_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::whatever::flight_mode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ec7751446dccbf592ba3e57dd292976";
  }

  static const char* value(const ::whatever::flight_mode_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ec7751446dccbf5ULL;
  static const uint64_t static_value2 = 0x92ba3e57dd292976ULL;
};

template<class ContainerAllocator>
struct DataType< ::whatever::flight_mode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "whatever/flight_mode";
  }

  static const char* value(const ::whatever::flight_mode_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::whatever::flight_mode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string flight_mode\n"
;
  }

  static const char* value(const ::whatever::flight_mode_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::whatever::flight_mode_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.flight_mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct flight_mode_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::whatever::flight_mode_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::whatever::flight_mode_<ContainerAllocator>& v)
  {
    s << indent << "flight_mode: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.flight_mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WHATEVER_MESSAGE_FLIGHT_MODE_H
