// Generated by gencpp from file whatever/override_motor.msg
// DO NOT EDIT!


#ifndef WHATEVER_MESSAGE_OVERRIDE_MOTOR_H
#define WHATEVER_MESSAGE_OVERRIDE_MOTOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace whatever
{
template <class ContainerAllocator>
struct override_motor_
{
  typedef override_motor_<ContainerAllocator> Type;

  override_motor_()
    : steering(0)
    , throttle(0)
    , header(0)  {
    }
  override_motor_(const ContainerAllocator& _alloc)
    : steering(0)
    , throttle(0)
    , header(0)  {
  (void)_alloc;
    }



   typedef int16_t _steering_type;
  _steering_type steering;

   typedef int16_t _throttle_type;
  _throttle_type throttle;

   typedef int16_t _header_type;
  _header_type header;





  typedef boost::shared_ptr< ::whatever::override_motor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::whatever::override_motor_<ContainerAllocator> const> ConstPtr;

}; // struct override_motor_

typedef ::whatever::override_motor_<std::allocator<void> > override_motor;

typedef boost::shared_ptr< ::whatever::override_motor > override_motorPtr;
typedef boost::shared_ptr< ::whatever::override_motor const> override_motorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::whatever::override_motor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::whatever::override_motor_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::whatever::override_motor_<ContainerAllocator1> & lhs, const ::whatever::override_motor_<ContainerAllocator2> & rhs)
{
  return lhs.steering == rhs.steering &&
    lhs.throttle == rhs.throttle &&
    lhs.header == rhs.header;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::whatever::override_motor_<ContainerAllocator1> & lhs, const ::whatever::override_motor_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace whatever

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::whatever::override_motor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::whatever::override_motor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::whatever::override_motor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::whatever::override_motor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::whatever::override_motor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::whatever::override_motor_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::whatever::override_motor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b0615c31df605e09b8a673bfb5e75c5e";
  }

  static const char* value(const ::whatever::override_motor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb0615c31df605e09ULL;
  static const uint64_t static_value2 = 0xb8a673bfb5e75c5eULL;
};

template<class ContainerAllocator>
struct DataType< ::whatever::override_motor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "whatever/override_motor";
  }

  static const char* value(const ::whatever::override_motor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::whatever::override_motor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 steering\n"
"int16 throttle\n"
"int16 header\n"
;
  }

  static const char* value(const ::whatever::override_motor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::whatever::override_motor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.steering);
      stream.next(m.throttle);
      stream.next(m.header);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct override_motor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::whatever::override_motor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::whatever::override_motor_<ContainerAllocator>& v)
  {
    s << indent << "steering: ";
    Printer<int16_t>::stream(s, indent + "  ", v.steering);
    s << indent << "throttle: ";
    Printer<int16_t>::stream(s, indent + "  ", v.throttle);
    s << indent << "header: ";
    Printer<int16_t>::stream(s, indent + "  ", v.header);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WHATEVER_MESSAGE_OVERRIDE_MOTOR_H
